
" This file is automatically generated by the script available at:
" <https://gitorious.org/mcinglis/vim-arduino>


if exists("b:current_syntax")
  finish
endif

runtime! syntax/cpp.vim


""" START AUTOGENERATED RULES

{{{RULES}}}
""" END AUTOGENERATED RULES


highlight default link arduinoType      Type
highlight default link arduinoConstant  Constant
highlight default link arduinoFunc      Function
highlight default link arduinoModule    Identifier

